server:
  port: ${PORT}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: ${JWT_SECRET}
  access:
    expiration: 1800000
  refresh:
    expiration: 604800000

front:
  url: ${FRONT_URL}

app:
  cookie:
    secure: true
    same-site: None
